/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sohai
 */
import java.sql.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.Color;
import javax.swing.*;
import java.awt.Toolkit;
import java.awt.event.*;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
public class StudentManager extends javax.swing.JFrame {

    /**
     * Creates new form StudentManager
     */
    
    //...................Logo code...........................
    
    ImageIcon logo = new ImageIcon("logo.png");
    Color selected = new Color(80,60, 60);
    Color unSelected = new Color(168, 124, 124);
    public StudentManager() {
        addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent e) {
                //Code for changing the Dashboard after adding a new staff
                txtStudentsDash();
                //Code for changing the Dashboard after adding a new staff
                txtStaffDash();
                //Code for changing the name of staff after adding/removing a new staff
                try{
                staff1.setText("" + staffTable.getValueAt(0,0));
                staff2.setText("" + staffTable.getValueAt(1,0));
                staff3.setText("" + staffTable.getValueAt(2,0));
                staff4.setText("" + staffTable.getValueAt(3,0));
                } catch (IndexOutOfBoundsException ex){
                    // there is not enough rows in the table to be in the dashboard
                }
                //Code for changing the name of staff after adding/removing a new course
                try{
                c1.setText("" + coursesTable.getValueAt(0,0));
                c2.setText("" + coursesTable.getValueAt(1,0));
                c3.setText("" + coursesTable.getValueAt(2,0));
                c4.setText("" + coursesTable.getValueAt(3,0));
                c5.setText("" + coursesTable.getValueAt(4,0));
                c6.setText("" + coursesTable.getValueAt(5,0));
                } catch (IndexOutOfBoundsException ex){
                    // there is not enough rows in the table to be in the dashboard
                }
            }
    });
        
        initComponents();
        this.setLocationRelativeTo(null);
        labelPic.setText("");
        labelPic.setIcon(logo);
    }
    //....................................

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        panel1 = new java.awt.Panel();
        labelPic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        studButton = new javax.swing.JButton();
        dashButton = new javax.swing.JButton();
        couButton = new javax.swing.JButton();
        gradButton = new javax.swing.JButton();
        staffButton = new javax.swing.JButton();
        mainTab = new javax.swing.JTabbedPane();
        Dashboard = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtStudentsDash = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtStaffDash = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        staff1 = new javax.swing.JLabel();
        staff2 = new javax.swing.JLabel();
        staff4 = new javax.swing.JLabel();
        staff3 = new javax.swing.JLabel();
        Students = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        addStud = new javax.swing.JButton();
        removeStud = new javax.swing.JButton();
        editStud = new javax.swing.JButton();
        clearStud = new javax.swing.JButton();
        Courses = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        clearCourse = new javax.swing.JButton();
        editCourse = new javax.swing.JButton();
        removeCourse = new javax.swing.JButton();
        addCourse = new javax.swing.JButton();
        Grades = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        gradeTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addGrades = new javax.swing.JButton();
        clearGrades = new javax.swing.JButton();
        editGrades = new javax.swing.JButton();
        removeGrades = new javax.swing.JButton();
        Staff = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        clearStaff = new javax.swing.JButton();
        editStaff = new javax.swing.JButton();
        removeStaff = new javax.swing.JButton();
        addStaff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colleague - Student Managment System");
        setLocation(new java.awt.Point(700, 250));
        setMinimumSize(new java.awt.Dimension(848, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(847, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(206, 195, 195));
        panel1.setPreferredSize(new java.awt.Dimension(847, 123));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPic.setText("jLabel1");
        labelPic.setMaximumSize(new java.awt.Dimension(283, 95));
        labelPic.setMinimumSize(new java.awt.Dimension(283, 95));
        labelPic.setPreferredSize(new java.awt.Dimension(283, 95));
        panel1.add(labelPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 15, -1, -1));
        labelPic.getAccessibleContext().setAccessibleName("labelPic");

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        jPanel2.setBackground(new java.awt.Color(62, 50, 50));

        studButton.setBackground(new java.awt.Color(168, 124, 124));
        studButton.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 24)); // NOI18N
        studButton.setForeground(new java.awt.Color(255, 255, 255));
        studButton.setText("Students");
        studButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        studButton.setBorderPainted(false);
        studButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studButton.setMaximumSize(new java.awt.Dimension(150, 50));
        studButton.setMinimumSize(new java.awt.Dimension(150, 50));
        studButton.setPreferredSize(new java.awt.Dimension(150, 50));
        studButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studButtonActionPerformed(evt);
            }
        });

        dashButton.setBackground(new java.awt.Color(80, 60, 60));
        dashButton.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 24)); // NOI18N
        dashButton.setForeground(new java.awt.Color(255, 255, 255));
        dashButton.setText("Dashboard");
        dashButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        dashButton.setBorderPainted(false);
        dashButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashButton.setFocusable(false);
        dashButton.setMaximumSize(new java.awt.Dimension(150, 50));
        dashButton.setMinimumSize(new java.awt.Dimension(150, 50));
        dashButton.setPreferredSize(new java.awt.Dimension(150, 50));
        dashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashButtonActionPerformed(evt);
            }
        });

        couButton.setBackground(new java.awt.Color(168, 124, 124));
        couButton.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 24)); // NOI18N
        couButton.setForeground(new java.awt.Color(255, 255, 255));
        couButton.setText("Courses");
        couButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        couButton.setBorderPainted(false);
        couButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        couButton.setMaximumSize(new java.awt.Dimension(150, 50));
        couButton.setMinimumSize(new java.awt.Dimension(150, 50));
        couButton.setPreferredSize(new java.awt.Dimension(150, 50));
        couButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couButtonActionPerformed(evt);
            }
        });

        gradButton.setBackground(new java.awt.Color(168, 124, 124));
        gradButton.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 24)); // NOI18N
        gradButton.setForeground(new java.awt.Color(255, 255, 255));
        gradButton.setText("Grades");
        gradButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        gradButton.setBorderPainted(false);
        gradButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gradButton.setMaximumSize(new java.awt.Dimension(150, 50));
        gradButton.setMinimumSize(new java.awt.Dimension(150, 50));
        gradButton.setPreferredSize(new java.awt.Dimension(150, 50));
        gradButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradButtonActionPerformed(evt);
            }
        });

        staffButton.setBackground(new java.awt.Color(168, 124, 124));
        staffButton.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 24)); // NOI18N
        staffButton.setForeground(new java.awt.Color(255, 255, 255));
        staffButton.setText("Staff");
        staffButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        staffButton.setBorderPainted(false);
        staffButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staffButton.setMaximumSize(new java.awt.Dimension(150, 50));
        staffButton.setMinimumSize(new java.awt.Dimension(150, 50));
        staffButton.setPreferredSize(new java.awt.Dimension(150, 50));
        staffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(dashButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(studButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(couButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(gradButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(staffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(couButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 860, 80));

        jPanel1.setBackground(new java.awt.Color(107, 99, 99));

        jLabel5.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Number of Students");
        jLabel5.setMaximumSize(new java.awt.Dimension(190, 59));
        jLabel5.setMinimumSize(new java.awt.Dimension(190, 59));
        jLabel5.setPreferredSize(new java.awt.Dimension(190, 59));

        txtStudentsDash.setBackground(new java.awt.Color(70, 60, 60));
        txtStudentsDash.setFont(new java.awt.Font("Fira Sans Extra Condensed Mediu", 1, 64)); // NOI18N
        txtStudentsDash.setForeground(new java.awt.Color(255, 255, 255));
        txtStudentsDash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStudentsDash.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtStudentsDash.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Recent Courses");

        c1.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 14)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c1.setText("OOP");
        c1.setToolTipText("");
        c1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        c2.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 14)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c2.setText("Discrete Maths");
        c2.setToolTipText("");
        c2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        c3.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 14)); // NOI18N
        c3.setForeground(new java.awt.Color(255, 255, 255));
        c3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c3.setText("Physics 2");
        c3.setToolTipText("");
        c3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        c5.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 14)); // NOI18N
        c5.setForeground(new java.awt.Color(255, 255, 255));
        c5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c5.setText("Signal Theory");
        c5.setToolTipText("");
        c5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        c6.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 14)); // NOI18N
        c6.setForeground(new java.awt.Color(255, 255, 255));
        c6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c6.setText("Circuit Theory");
        c6.setToolTipText("");
        c6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        c4.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 14)); // NOI18N
        c4.setForeground(new java.awt.Color(255, 255, 255));
        c4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c4.setText("Math 2");
        c4.setToolTipText("");
        c4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Number of Staff");
        jLabel14.setMaximumSize(new java.awt.Dimension(190, 59));
        jLabel14.setMinimumSize(new java.awt.Dimension(190, 59));
        jLabel14.setPreferredSize(new java.awt.Dimension(190, 59));

        txtStaffDash.setBackground(new java.awt.Color(70, 60, 60));
        txtStaffDash.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 64)); // NOI18N
        txtStaffDash.setForeground(new java.awt.Color(255, 255, 255));
        txtStaffDash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStaffDash.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtStaffDash.setOpaque(true);

        jLabel16.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Recent Staff");

        staff1.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 14)); // NOI18N
        staff1.setForeground(new java.awt.Color(255, 255, 255));
        staff1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staff1.setText("Dr. Youssef Kareem");
        staff1.setToolTipText("");
        staff1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        staff2.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 14)); // NOI18N
        staff2.setForeground(new java.awt.Color(255, 255, 255));
        staff2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staff2.setText("Dr. Zeyad el-Bek");
        staff2.setToolTipText("");
        staff2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        staff4.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 14)); // NOI18N
        staff4.setForeground(new java.awt.Color(255, 255, 255));
        staff4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staff4.setText("Dr. Essam Omar");
        staff4.setToolTipText("");
        staff4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        staff3.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 14)); // NOI18N
        staff3.setForeground(new java.awt.Color(255, 255, 255));
        staff3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staff3.setText("Dr. Salah Ahmed");
        staff3.setToolTipText("");
        staff3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)
                                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtStudentsDash, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(staff1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staff2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(staff3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staff4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtStaffDash, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStaffDash, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentsDash, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staff1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staff2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staff3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staff4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        Dashboard.addTab("tab1", jPanel1);

        mainTab.addTab("tab1", Dashboard);

        jPanel3.setBackground(new java.awt.Color(206, 195, 195));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentsTable.setAutoCreateRowSorter(true);
        studentsTable.setBackground(new java.awt.Color(206, 195, 195));
        studentsTable.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 12)); // NOI18N
        studentsTable.setForeground(new java.awt.Color(62, 50, 50));
        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ahmed", "2039482", "4", "3"}
            },
            new String [] {
                "Name", "ID", "GPA", "Level"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentsTable.setFocusable(false);
        studentsTable.setRowHeight(24);
        studentsTable.setSelectionBackground(new java.awt.Color(70, 60, 60));
        studentsTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        studentsTable.setShowGrid(true);
        studentsTable.setShowHorizontalLines(false);
        studentsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(studentsTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 720, 470));

        jPanel4.setBackground(new java.awt.Color(80, 60, 60));

        addStud.setBackground(new java.awt.Color(62, 50, 50));
        addStud.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 18)); // NOI18N
        addStud.setForeground(new java.awt.Color(255, 255, 255));
        addStud.setText("Add");
        addStud.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        addStud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudActionPerformed(evt);
            }
        });

        removeStud.setBackground(new java.awt.Color(62, 50, 50));
        removeStud.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 18)); // NOI18N
        removeStud.setForeground(new java.awt.Color(255, 255, 255));
        removeStud.setText("Remove");
        removeStud.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        removeStud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudActionPerformed(evt);
            }
        });

        editStud.setBackground(new java.awt.Color(62, 50, 50));
        editStud.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 18)); // NOI18N
        editStud.setForeground(new java.awt.Color(255, 255, 255));
        editStud.setText("Edit");
        editStud.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        editStud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudActionPerformed(evt);
            }
        });

        clearStud.setBackground(new java.awt.Color(62, 50, 50));
        clearStud.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 18)); // NOI18N
        clearStud.setForeground(new java.awt.Color(255, 255, 255));
        clearStud.setText("Clear");
        clearStud.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        clearStud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearStudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStud, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeStud, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStud, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearStud, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(addStud, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(removeStud, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(editStud, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(clearStud, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 470));

        Students.addTab("tab1", jPanel3);

        mainTab.addTab("tab1", Students);

        jPanel5.setBackground(new java.awt.Color(206, 195, 195));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coursesTable.setAutoCreateRowSorter(true);
        coursesTable.setBackground(new java.awt.Color(206, 195, 195));
        coursesTable.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 14)); // NOI18N
        coursesTable.setForeground(new java.awt.Color(62, 50, 50));
        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Credit Hours", "NO. Enrolled"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        coursesTable.setColumnSelectionAllowed(true);
        coursesTable.setFocusable(false);
        coursesTable.setRowHeight(24);
        coursesTable.setSelectionBackground(new java.awt.Color(70, 60, 60));
        coursesTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        coursesTable.setShowGrid(true);
        coursesTable.setShowHorizontalLines(false);
        coursesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(coursesTable);
        coursesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 720, 470));

        jPanel8.setBackground(new java.awt.Color(80, 60, 60));

        clearCourse.setBackground(new java.awt.Color(62, 50, 50));
        clearCourse.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 18)); // NOI18N
        clearCourse.setForeground(new java.awt.Color(255, 255, 255));
        clearCourse.setText("Clear");
        clearCourse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        clearCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCourseActionPerformed(evt);
            }
        });

        editCourse.setBackground(new java.awt.Color(62, 50, 50));
        editCourse.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 18)); // NOI18N
        editCourse.setForeground(new java.awt.Color(255, 255, 255));
        editCourse.setText("Edit");
        editCourse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        editCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCourseActionPerformed(evt);
            }
        });

        removeCourse.setBackground(new java.awt.Color(62, 50, 50));
        removeCourse.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 18)); // NOI18N
        removeCourse.setForeground(new java.awt.Color(255, 255, 255));
        removeCourse.setText("Remove");
        removeCourse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        removeCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCourseActionPerformed(evt);
            }
        });

        addCourse.setBackground(new java.awt.Color(62, 50, 50));
        addCourse.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 18)); // NOI18N
        addCourse.setForeground(new java.awt.Color(255, 255, 255));
        addCourse.setText("Add");
        addCourse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        addCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(addCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(removeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(editCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(clearCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 470));

        Courses.addTab("tab1", jPanel5);

        mainTab.addTab("tab3", Courses);

        jPanel12.setBackground(new java.awt.Color(114, 99, 99));

        jPanel13.setBackground(new java.awt.Color(206, 195, 195));

        jLabel1.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter the Student's ID:");

        jTextField1.setBackground(new java.awt.Color(126, 99, 99));
        jTextField1.setFont(new java.awt.Font("Fira Sans Extra Condensed Mediu", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("1290391");
        jTextField1.setBorder(null);

        jScrollPane5.setBackground(new java.awt.Color(114, 99, 99));

        gradeTable.setBackground(new java.awt.Color(114, 99, 99));
        gradeTable.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 14)); // NOI18N
        gradeTable.setForeground(new java.awt.Color(255, 255, 255));
        gradeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Communication Technology", "100", "A+"},
                {"Discrete Maths", "100", "A+"},
                {"Object Oriented Programming", "100", "A+"},
                {"Math 2", "100", "A+"}
            },
            new String [] {
                "Course Name", "Mark (Max. 100)", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradeTable.setFocusable(false);
        gradeTable.setGridColor(new java.awt.Color(255, 255, 255));
        gradeTable.setRowMargin(3);
        gradeTable.setSelectionBackground(new java.awt.Color(223, 204, 204));
        gradeTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        gradeTable.setShowGrid(true);
        gradeTable.setShowHorizontalLines(false);
        gradeTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(gradeTable);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GPA:");

        jLabel3.setBackground(new java.awt.Color(168, 124, 124));
        jLabel3.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("4");
        jLabel3.setOpaque(true);

        addGrades.setBackground(new java.awt.Color(126, 99, 99));
        addGrades.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 24)); // NOI18N
        addGrades.setForeground(new java.awt.Color(255, 255, 255));
        addGrades.setText("Add");
        addGrades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        addGrades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addGrades.setFocusable(false);
        addGrades.setMaximumSize(new java.awt.Dimension(150, 50));
        addGrades.setMinimumSize(new java.awt.Dimension(150, 50));
        addGrades.setPreferredSize(new java.awt.Dimension(150, 50));
        addGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGradesActionPerformed(evt);
            }
        });

        clearGrades.setBackground(new java.awt.Color(126, 99, 99));
        clearGrades.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 24)); // NOI18N
        clearGrades.setForeground(new java.awt.Color(255, 255, 255));
        clearGrades.setText("Clear");
        clearGrades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        clearGrades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearGrades.setFocusable(false);
        clearGrades.setMaximumSize(new java.awt.Dimension(150, 50));
        clearGrades.setMinimumSize(new java.awt.Dimension(150, 50));
        clearGrades.setPreferredSize(new java.awt.Dimension(150, 50));
        clearGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearGradesActionPerformed(evt);
            }
        });

        editGrades.setBackground(new java.awt.Color(126, 99, 99));
        editGrades.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 24)); // NOI18N
        editGrades.setForeground(new java.awt.Color(255, 255, 255));
        editGrades.setText("Edit");
        editGrades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        editGrades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editGrades.setFocusable(false);
        editGrades.setMaximumSize(new java.awt.Dimension(150, 50));
        editGrades.setMinimumSize(new java.awt.Dimension(150, 50));
        editGrades.setPreferredSize(new java.awt.Dimension(150, 50));
        editGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGradesActionPerformed(evt);
            }
        });

        removeGrades.setBackground(new java.awt.Color(126, 99, 99));
        removeGrades.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 1, 24)); // NOI18N
        removeGrades.setForeground(new java.awt.Color(255, 255, 255));
        removeGrades.setText("Remove");
        removeGrades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        removeGrades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeGrades.setFocusable(false);
        removeGrades.setMaximumSize(new java.awt.Dimension(150, 50));
        removeGrades.setMinimumSize(new java.awt.Dimension(150, 50));
        removeGrades.setPreferredSize(new java.awt.Dimension(150, 50));
        removeGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeGradesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(removeGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addGrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeGrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearGrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editGrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(73, 73, 73))))
        );

        Grades.addTab("tab1", jPanel12);

        mainTab.addTab("tab1", Grades);

        jPanel9.setBackground(new java.awt.Color(206, 195, 195));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffTable.setAutoCreateRowSorter(true);
        staffTable.setBackground(new java.awt.Color(206, 195, 195));
        staffTable.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 14)); // NOI18N
        staffTable.setForeground(new java.awt.Color(62, 50, 50));
        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Ahmed", "20349234", "011234345"}
            },
            new String [] {
                "Professor's Name", "ID", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        staffTable.setColumnSelectionAllowed(true);
        staffTable.setFocusable(false);
        staffTable.setRowHeight(24);
        staffTable.setSelectionBackground(new java.awt.Color(70, 60, 60));
        staffTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        staffTable.setShowGrid(true);
        staffTable.setShowHorizontalLines(false);
        staffTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(staffTable);
        staffTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 721, 470));

        jPanel11.setBackground(new java.awt.Color(80, 60, 60));

        clearStaff.setBackground(new java.awt.Color(62, 50, 50));
        clearStaff.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 18)); // NOI18N
        clearStaff.setForeground(new java.awt.Color(255, 255, 255));
        clearStaff.setText("Clear");
        clearStaff.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        clearStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearStaffActionPerformed(evt);
            }
        });

        editStaff.setBackground(new java.awt.Color(62, 50, 50));
        editStaff.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 18)); // NOI18N
        editStaff.setForeground(new java.awt.Color(255, 255, 255));
        editStaff.setText("Edit");
        editStaff.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        editStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStaffActionPerformed(evt);
            }
        });

        removeStaff.setBackground(new java.awt.Color(62, 50, 50));
        removeStaff.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 18)); // NOI18N
        removeStaff.setForeground(new java.awt.Color(255, 255, 255));
        removeStaff.setText("Remove");
        removeStaff.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        removeStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStaffActionPerformed(evt);
            }
        });

        addStaff.setBackground(new java.awt.Color(62, 50, 50));
        addStaff.setFont(new java.awt.Font("Fira Sans Extra Condensed Medium", 0, 18)); // NOI18N
        addStaff.setForeground(new java.awt.Color(255, 255, 255));
        addStaff.setText("Add");
        addStaff.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        addStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(addStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(removeStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(editStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(clearStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 470));

        Staff.addTab("tab1", jPanel9);

        mainTab.addTab("tab1", Staff);

        getContentPane().add(mainTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 140, 870, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
       public void txtStudentsDash() {
        // Update the text of the label with the row count of the table
        txtStudentsDash.setText(""+studentsTable.getRowCount());
    }
       public void txtStaffDash() {
        // Update the text of the label with the row count of the table
        txtStaffDash.setText(""+staffTable.getRowCount());
    }
       
    private void dashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashButtonActionPerformed
        mainTab.setSelectedIndex(0);
        dashButton.setBackground(selected);
        staffButton.setBackground(unSelected);
        studButton.setBackground(unSelected);
        couButton.setBackground(unSelected);
        gradButton.setBackground(unSelected);
                //Code for changing the Dashboard after adding a new staff
                txtStudentsDash();
                //Code for changing the Dashboard after adding a new staff
                txtStaffDash();
                //Code for changing the name of staff after adding/removing a new staff
                try{
                staff1.setText("" + staffTable.getValueAt(0,0));
                staff2.setText("" + staffTable.getValueAt(1,0));
                staff3.setText("" + staffTable.getValueAt(2,0));
                staff4.setText("" + staffTable.getValueAt(3,0));
                } catch (IndexOutOfBoundsException ex){
                    // there is not enough rows in the table to be in the dashboard
                }
                //Code for changing the name of staff after adding/removing a new course
                try{
                c1.setText("" + coursesTable.getValueAt(0,0));
                c2.setText("" + coursesTable.getValueAt(1,0));
                c3.setText("" + coursesTable.getValueAt(2,0));
                c4.setText("" + coursesTable.getValueAt(3,0));
                c5.setText("" + coursesTable.getValueAt(4,0));
                c6.setText("" + coursesTable.getValueAt(5,0));
                } catch (IndexOutOfBoundsException ex){
                    // there is not enough rows in the table to be in the dashboard
                }
    }//GEN-LAST:event_dashButtonActionPerformed

    private void studButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studButtonActionPerformed
        mainTab.setSelectedIndex(1);
        dashButton.setBackground(unSelected);
        staffButton.setBackground(unSelected);
        studButton.setBackground(selected);
        couButton.setBackground(unSelected);
        gradButton.setBackground(unSelected);
    }//GEN-LAST:event_studButtonActionPerformed

    private void couButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couButtonActionPerformed
        mainTab.setSelectedIndex(2);
        dashButton.setBackground(unSelected);
        staffButton.setBackground(unSelected);
        studButton.setBackground(unSelected);
        couButton.setBackground(selected);
        gradButton.setBackground(unSelected);
    }//GEN-LAST:event_couButtonActionPerformed

    private void gradButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradButtonActionPerformed
        mainTab.setSelectedIndex(3);
        dashButton.setBackground(unSelected);
        staffButton.setBackground(unSelected);
        studButton.setBackground(unSelected);
        couButton.setBackground(unSelected);
        gradButton.setBackground(selected);
    }//GEN-LAST:event_gradButtonActionPerformed

    private void staffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffButtonActionPerformed
        mainTab.setSelectedIndex(4);
        dashButton.setBackground(unSelected);
        staffButton.setBackground(selected);
        studButton.setBackground(unSelected);
        couButton.setBackground(unSelected);
        gradButton.setBackground(unSelected);
    }//GEN-LAST:event_staffButtonActionPerformed

    private void addGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGradesActionPerformed
        addGradeFrame gradeFrame = new addGradeFrame();
        gradeFrame.setVisible(true);
    }//GEN-LAST:event_addGradesActionPerformed

    private void addStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudActionPerformed
        addStudentFrame studFrame = new addStudentFrame();
        studFrame.setVisible(true);
    }//GEN-LAST:event_addStudActionPerformed

    private void addStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffActionPerformed
        addStaffFrame staffFrame = new addStaffFrame();
        staffFrame.setVisible(true);
    }//GEN-LAST:event_addStaffActionPerformed

    private void addCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseActionPerformed
        addCourseFrame courseFrame = new addCourseFrame();
        courseFrame.setVisible(true);
    }//GEN-LAST:event_addCourseActionPerformed

    private void editStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStaffActionPerformed
        if(staffTable.getSelectedRowCount()==1){
            editStaffFrame editStaff = new editStaffFrame();
            editStaff.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Please Select one row to be Edited!");
        }
    }//GEN-LAST:event_editStaffActionPerformed

    private void editStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudActionPerformed
        if(studentsTable.getSelectedRowCount() == 1){
            editStudentFrame editStudent = new editStudentFrame();
            editStudent.setVisible(true);  
        } else {
            JOptionPane.showMessageDialog(this, "Please Select one row to be Edited!");
        }
    }//GEN-LAST:event_editStudActionPerformed

    private void editGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGradesActionPerformed
        if(gradeTable.getSelectedRowCount()==1){
            editGradeFrame editGrade = new editGradeFrame();
            editGrade.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Please Select one row to be Edited!");
        }
    }//GEN-LAST:event_editGradesActionPerformed

    private void editCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCourseActionPerformed
        if(coursesTable.getSelectedRowCount()==1){
            editCourseFrame editCourse = new editCourseFrame();
            editCourse.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Please Select one row to be Edited!");
        }
    }//GEN-LAST:event_editCourseActionPerformed

    private void removeStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStaffActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)(StudentManager.getStaffTable()).getModel(); 
        if(staffTable.getSelectedRow() != -1) {
               // remove selected row from the model
               tableModel.removeRow(staffTable.getSelectedRow());
               JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
        }else {
            JOptionPane.showMessageDialog(null, "Please select one row to be removed!");
        }
    }//GEN-LAST:event_removeStaffActionPerformed

    private void removeGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeGradesActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)(StudentManager.getGradeTable()).getModel(); 
        if(gradeTable.getSelectedRow() != -1) {
               // remove selected row from the model
               tableModel.removeRow(gradeTable.getSelectedRow());
               JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Please select one row to be removed!");
        }
    }//GEN-LAST:event_removeGradesActionPerformed

    private void removeCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCourseActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)(StudentManager.getCoursesTable()).getModel(); 
        if(coursesTable.getSelectedRow() != -1) {
               // remove selected row from the model
               tableModel.removeRow(coursesTable.getSelectedRow());
               JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
        }else {
            JOptionPane.showMessageDialog(null, "Please select one row to be removed!");
        }
    }//GEN-LAST:event_removeCourseActionPerformed

    private void removeStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)(StudentManager.getStudentsTable()).getModel(); 
        if(studentsTable.getSelectedRow() != -1) {
               // remove selected row from the model
               tableModel.removeRow(studentsTable.getSelectedRow());
               JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
        }else {
            JOptionPane.showMessageDialog(null, "Please select one row to be removed!");
        }
    }//GEN-LAST:event_removeStudActionPerformed

    private void clearStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearStudActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)(StudentManager.getStudentsTable()).getModel(); 
        tableModel.setRowCount(0);
        JOptionPane.showMessageDialog(null, "The table has been cleared successfully");
    }//GEN-LAST:event_clearStudActionPerformed

    private void clearCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCourseActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)(StudentManager.getCoursesTable()).getModel();
        tableModel.setRowCount(0);
        JOptionPane.showMessageDialog(null, "The table has been cleared successfully");
    }//GEN-LAST:event_clearCourseActionPerformed

    private void clearGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearGradesActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)(StudentManager.getGradeTable()).getModel(); 
        tableModel.setRowCount(0);
        JOptionPane.showMessageDialog(null, "The table has been cleared successfully");
    }//GEN-LAST:event_clearGradesActionPerformed

    private void clearStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearStaffActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel)(StudentManager.getStaffTable()).getModel(); 
        tableModel.setRowCount(0);
        JOptionPane.showMessageDialog(null, "The table has been cleared successfully");
    }//GEN-LAST:event_clearStaffActionPerformed

    public static javax.swing.JTable getStudentsTable()
    {
        return studentsTable;
    }
        public static javax.swing.JTable getCoursesTable()
    {
        return coursesTable;
    }
    public static javax.swing.JTable getGradeTable()
    {
        return gradeTable;
    }
    public static javax.swing.JTable getStaffTable()
    {
        return staffTable;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManager().setVisible(true);
            }
        });

    }
    
    public void close (){
            WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Courses;
    private javax.swing.JTabbedPane Dashboard;
    private javax.swing.JTabbedPane Grades;
    private javax.swing.JTabbedPane Staff;
    private javax.swing.JTabbedPane Students;
    private javax.swing.JButton addCourse;
    private javax.swing.JButton addGrades;
    private javax.swing.JButton addStaff;
    private javax.swing.JButton addStud;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JButton clearCourse;
    private javax.swing.JButton clearGrades;
    private javax.swing.JButton clearStaff;
    private javax.swing.JButton clearStud;
    private javax.swing.JButton couButton;
    private static javax.swing.JTable coursesTable;
    private javax.swing.JButton dashButton;
    private javax.swing.JButton editCourse;
    private javax.swing.JButton editGrades;
    private javax.swing.JButton editStaff;
    private javax.swing.JButton editStud;
    private javax.swing.JButton gradButton;
    private static javax.swing.JTable gradeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelPic;
    private javax.swing.JTabbedPane mainTab;
    private java.awt.Panel panel1;
    private javax.swing.JButton removeCourse;
    private javax.swing.JButton removeGrades;
    private javax.swing.JButton removeStaff;
    private javax.swing.JButton removeStud;
    private javax.swing.JLabel staff1;
    private javax.swing.JLabel staff2;
    private javax.swing.JLabel staff3;
    private javax.swing.JLabel staff4;
    private javax.swing.JButton staffButton;
    private static javax.swing.JTable staffTable;
    private javax.swing.JButton studButton;
    private static javax.swing.JTable studentsTable;
    private javax.swing.JLabel txtStaffDash;
    private javax.swing.JLabel txtStudentsDash;
    // End of variables declaration//GEN-END:variables
}
